
export const sendOrder = async (params) => {

  try {

  } catch (err) {
    throw new Error("Error sending order");
  }
};
